name: watch_fox
description: "Watch Fox V2 Application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Communication réseau
  http: ^1.1.0
  
  # Sécurité et Hachage
  crypto: ^3.0.3
  
  # Utilise exactement cette version pour la compatibilité avec ton code actuel
  libphonenumber: ^2.0.0
  
  # Remplacement de l'ancien 'dns' pour éviter les erreurs de build

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/background.png
    - assets/logo.png